---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: network-ingress-nginx-certificates
  namespace: flux-system
spec:
  path: ./cluster/apps/network/ingress-nginx/certificates
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
  dependsOn:
    - name: kube-system-cert-manager-issuers
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: network-ingress-nginx
  namespace: flux-system
spec:
  path: ./cluster/apps/network/ingress-nginx/app
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
  dependsOn:
    - name: network-ingress-nginx-certificates
