---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: network-echo-server
  namespace: flux-system
spec:
  path: "./cluster/apps/network/echo-server/app"
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
