---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-echo-server
  namespace: flux-system
spec:
  path: "./cluster/apps/network/echo-server/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  interval: 10m
  wait: true
