---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-metallb
  namespace: flux-system
spec:
  path: ./cluster/apps/networking/metallb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: metallb
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-metallb
  path: ./cluster/apps/networking/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
