---
creation_rules:
  - path_regex: setup/talos/.*.enc.ya?ml
    age: >-
      age17qng9yfpg5kxrxvy0rjs2ve35w2t6vexz629ys4am4gtyjpflgzqxq2s0l
  - path_regex: setup/talos/.*/.*.enc.ya?ml
    encrypted_regex: "((?i)(pass|secret($|[^N])|ca|crt|key|token|^data$|^stringData$))"
    age: >-
      age17qng9yfpg5kxrxvy0rjs2ve35w2t6vexz629ys4am4gtyjpflgzqxq2s0l
  - path_regex: .*/*.enc.ya?ml
    encrypted_regex: ^(data|stringData)$
    unencrypted-regex: ^(description|metadata)$
    age: >-
      age17qng9yfpg5kxrxvy0rjs2ve35w2t6vexz629ys4am4gtyjpflgzqxq2s0l
