---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-configmap
  namespace: network
data:
  config.yaml: |
    ingress:
      - hostname: "*.${DOMAIN}"
        service: https://ingress-nginx-controller.network.svc.cluster.local:443
        originRequest:
          originServerName: "ingress.${DOMAIN}"
      - service: http_status:404
