---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared-tunnel
  namespace: network
  annotations:
    external-dns.alpha.kubernetes.io/target: &host "ingress.${DOMAIN}"
spec:
  endpoints:
    - dnsName: *host
      recordType: CNAME
      targets: ["c0c9acab-b5b5-4513-9de9-5c7a800a6d4a.cfargotunnel.com"]
