---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - dns-endpoint.yaml
  - secret.enc.yaml
  - helm-release.yaml
configMapGenerator:
  - name: cloudflared-configmap
    files:
      - ./config.yaml
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  app.kubernetes.io/name: cloudflared
  app.kubernetes.io/instance: cloudflared
