---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system-flux-notifications
  namespace: flux-system
spec:
  path: ./cluster/apps/flux-system/addons/notifications
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system-flux-webhooks
  namespace: flux-system
spec:
  path: ./cluster/apps/flux-system/addons/webhooks
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
