---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-flux-notifications
  namespace: flux-system
spec:
  path: ./cluster/apps/flux-system/addons/notifications
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-flux-webhooks
  namespace: flux-system
spec:
  path: ./cluster/apps/flux-system/addons/webhooks
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
