---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-cloudflared
  namespace: flux-system
spec:
  interval: 10m
  path: "./cluster/apps/network/cloudflared/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
  dependsOn:
    - name: apps-externaldns-shared
