---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: network-cloudflared
  namespace: flux-system
spec:
  path: "./cluster/apps/network/cloudflared/app"
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
  dependsOn:
    - name: network-externaldns-external
