---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-kyverno
  namespace: flux-system
spec:
  interval: 10m
  path: "./cluster/apps/kyverno/kyverno/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-kyverno-policies
  namespace: flux-system
spec:
  interval: 10m
  path: "./cluster/apps/kyverno/kyverno/policies"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
  dependsOn:
    - name: apps-kyverno
