---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno-kyverno
  namespace: flux-system
spec:
  path: "./cluster/apps/kyverno/kyverno/app"
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  path: "./cluster/apps/kyverno/kyverno/policies"
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
  dependsOn:
    - name: kyverno-kyverno
