---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-k8s-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-metallb
    - name: apps-metallb-config
  path: ./cluster/apps/networking/k8s-gateway/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: k8s-gateway
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
