---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-externaldns-shared
  namespace: flux-system
spec:
  interval: 10m
  path: "./cluster/apps/network/external-dns/shared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-externaldns-external
  namespace: flux-system
spec:
  interval: 10m
  path: "./cluster/apps/network/external-dns/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
  dependsOn:
    - name: apps-externaldns-shared
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-externaldns-internal
  namespace: flux-system
spec:
  interval: 10m
  path: "./cluster/apps/network/external-dns/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
