---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: network-externaldns-external
  namespace: flux-system
spec:
  path: "./cluster/apps/network/external-dns/external"
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: network-externaldns-internal
  namespace: flux-system
spec:
  path: "./cluster/apps/network/external-dns/internal"
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
