apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: externaldns-external-secrets
    namespace: network
stringData:
    cloudflare_api_token: ENC[AES256_GCM,data:nlS8TlEvuJ+AZmyv12nYqBkBWMEOeSSuDnvftysB,iv:P054CxeA6emAZYLVP386VG3Qp55I11TuNNJSwhYhVEQ=,tag:vzTwSNTiSdOB3Z0MptB8jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17qng9yfpg5kxrxvy0rjs2ve35w2t6vexz629ys4am4gtyjpflgzqxq2s0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcTVJT0JCL3d6VXR2Qm5v
            VzhkdGJzV05XNmZtUjVnSlU0UDFVZzZKam04CmpoNzk0NXZ3dlorMzhvRHRuQmRC
            cjFFY1cvbXBjUlprRlNjRmp6U1RuWkEKLS0tIHlLZXBvYzgzK2x4UFYxajlBRzdq
            dWUxdVA3azRydGVhK0lSdGcxcGsyRUEK03vFp8U+PXPxP8FMS5ZojPNqeSOypNoK
            WTFWSIvv4Voo7F6OsiykfaDSwYpbV0bLQKfvd1iqHOrx04BcK2POyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-12T15:13:07Z"
    mac: ENC[AES256_GCM,data:++z42s7vlBqbke4YS4Qtcs2VeU6n6dgti2rDeiY4Ln4+3P2xkpQ/FrekJUfV3cplBZ4NdGddlekmHaWF/33CmY9nCOQqk9TIhTzlE+VObTih+tRN7uqM/jpQiCIuDUufuTHuYTEeqNK4YdY/dL44hTaCoKpDP3qBCMdTdHvsy2s=,iv:KZj7VG2k9QSKP4NYMX2sDqyhIedbxMZwlAQXks5/mRk=,tag:depEsknFNKgeYOT+7eHPEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
