---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system-weave-gitops
  namespace: flux-system
spec:
  path: ./cluster/apps/flux-system/weave-gitops/app
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
