---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-rook-ceph
  namespace: flux-system
spec:
  path: "./cluster/apps/rook-ceph/rook-ceph/operator"
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-rook-ceph-cluster
  namespace: flux-system
spec:
  path: "./cluster/apps/rook-ceph/rook-ceph/cluster"
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
  dependsOn:
    - name: rook-ceph-rook-ceph
