---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-rook-ceph
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/apps/rook-ceph/rook-ceph/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-rook-ceph-cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/apps/rook-ceph/rook-ceph/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
  dependsOn:
    - name: apps-rook-ceph
