---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-descheduler
  namespace: flux-system
spec:
  interval: 10m
  path: "./cluster/apps/system/descheduler/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
