---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-ingress-nginx-certificates
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: apps-cert-manager-issuers
  path: ./cluster/apps/networking/ingress-nginx/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  # wait: true
  install:
    disableWait: true
  upgrade:
    disableWait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-ingress-nginx-certificates
    - name: apps-metallb-config
  path: ./cluster/apps/networking/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ingress-nginx
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
