apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:lQ04PPjxueC4M86eYJ1rzcvk1hfVOXr1+YE=,iv:TC9K3KQLaiIAy3WEF2+pwZOn2gUmNMzNTn6h8b8ls+U=,tag:Cc83FjPUrveYWIHEiIqb6g==,type:str]
    api-key: ENC[AES256_GCM,data:K2poP2/5OX1/B4q6i7xJ4zlwYCe1Dsf8EYtj2w==,iv:5FvsvEoT4S2LgTc5uP4tGpRDzLqPqQdgwJkQuSEJBPA=,tag:dMc2lzqWu/FtsWhcQE2Z5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17qng9yfpg5kxrxvy0rjs2ve35w2t6vexz629ys4am4gtyjpflgzqxq2s0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUGllSGJLNmRhQVMzSGpJ
            T2NOQm9pV0hOck5tb3pRTzh3NkRKOXAyUWhvCkJKTFJhQWx6U0dRMEE4aFRjVmlO
            Z0ljUXZxMHBTNCs0cThza0NOSHNlNGcKLS0tIEpkMjM5UEFZY09td1luSkRqMjN2
            Tk1zeGFybGt1bGVSY2ZJSGtlT0F5TTgKmmjtrMg47wg6CEDWx/m8a5ncZ0fr4b+f
            QQZetx08olqyrQoP5KRrM9YcjCot5wDrVVVpSrefOgAA1lafLd9FmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-08T23:37:47Z"
    mac: ENC[AES256_GCM,data:fSZN7OSzyoAeyQSDFDKIFmyovBM3KLq8ZRU02CUSsYmmVhdLiCpyyemehRRavijNI+zkwPQxRSJCRxA22Gb7FzGBdD/Q+RavrxD5GIfzIA8AgwP+Q/tz6RHvMZlw8gsurfjOsByf2dPzfKbAXNV4OJg0NouStTVfKKeevnotGzw=,iv:CDQsnCIoR20y3T+HRUJK8z9nFXvOCRXoUkQ3Ddt5hYM=,tag:ynGHSJzYqt2PdckGEdLKvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
