apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:lRw9LqLQNeG0zkSXRoM7CU0=,iv:RfynFsVBLBTYm4+MykiHckHvnR9ruI5SC96ADPXiKIM=,tag:JhaYasstDjfeg2vEfsrSHw==,type:str]
    token: ENC[AES256_GCM,data:tXnumap5d83Y6LWyM8HIVYBjhWGwnBmwZdbNU1JxlY6VmXbCSmJJEg==,iv:qcTgl6VgZb974ZLcjblPiNhiPOpFxkW1wQF8kKDiom0=,tag:oTj5pvgINXUp1TdDWbr4qQ==,type:str]
    api-key: ENC[AES256_GCM,data:3gYQTaQg1vKAYtzg8uGnowrCktYKuPewKwl3nCHdTKvgkV7IxGVbdw==,iv:1zmtTyiaa3E73Md7Si6RkWn1QPKrozfgQ8VS3OaH5NU=,tag:lsfC/QGFGKtKnTsLR3beHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17qng9yfpg5kxrxvy0rjs2ve35w2t6vexz629ys4am4gtyjpflgzqxq2s0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUGllSGJLNmRhQVMzSGpJ
            T2NOQm9pV0hOck5tb3pRTzh3NkRKOXAyUWhvCkJKTFJhQWx6U0dRMEE4aFRjVmlO
            Z0ljUXZxMHBTNCs0cThza0NOSHNlNGcKLS0tIEpkMjM5UEFZY09td1luSkRqMjN2
            Tk1zeGFybGt1bGVSY2ZJSGtlT0F5TTgKmmjtrMg47wg6CEDWx/m8a5ncZ0fr4b+f
            QQZetx08olqyrQoP5KRrM9YcjCot5wDrVVVpSrefOgAA1lafLd9FmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-05T23:47:17Z"
    mac: ENC[AES256_GCM,data:MD6FFZLcWyWfwB6VZBbOF0+uZ46RMwyebBOco17azO6ijqL0mHREwEcex3qxKgY9V3Fuyrmj3jlKVXKVS9Nr+6nyVllDyHnkwpQc1ST52MoioAtChjFyW877nCDzxVb5KX8qRM9fQ8Q40OCKWxWDj2r1W2tcNmjvnyT2FoYrZ2Y=,iv:ehAw8ZX4just91Wy0eR/OzYY2iDCpqc2eCE6KYlkZAA=,tag:SSARMdPfnlAI6GqrUpogMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
