apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    token: ENC[AES256_GCM,data:f056urdJRcET1eGRdlxsPf+LHOSEt9RYFrr5SvQL,iv:zTy5IpRo6qkqt7sJoCRTJxyw7mg5J4NWguQTdWLqmtE=,tag:ibFg0WmfLIYodT/k1vDxIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17qng9yfpg5kxrxvy0rjs2ve35w2t6vexz629ys4am4gtyjpflgzqxq2s0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUGllSGJLNmRhQVMzSGpJ
            T2NOQm9pV0hOck5tb3pRTzh3NkRKOXAyUWhvCkJKTFJhQWx6U0dRMEE4aFRjVmlO
            Z0ljUXZxMHBTNCs0cThza0NOSHNlNGcKLS0tIEpkMjM5UEFZY09td1luSkRqMjN2
            Tk1zeGFybGt1bGVSY2ZJSGtlT0F5TTgKmmjtrMg47wg6CEDWx/m8a5ncZ0fr4b+f
            QQZetx08olqyrQoP5KRrM9YcjCot5wDrVVVpSrefOgAA1lafLd9FmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-06T00:08:38Z"
    mac: ENC[AES256_GCM,data:uigS16bWsQo6B8NBW25hWCx+vkIHVBGbU3MhbhFocI710DAGI0HQuBG22hF2FS42C2jiO05YoQgdHPNq+uwE1pfkTVdki/bk3hD/Prqif8S3HEnwS7X9/VQK7J96SjhqkCWWDnYKzkpHK51No30O9w3nV+PI7OnezImaz0Gug9o=,iv:TqmAyVBfCtnx85KRHPahAxmFMMU3A57i14gkxQ2tHsg=,tag:mrhCknzdC/WGEimMpL+ARg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
