---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN/./-}-prod"
  namespace: network
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kasten-io"
  secretName: "${DOMAIN/./-}-prod-tls"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "${DOMAIN}"
  dnsNames:
    - "${DOMAIN}"
    - "*.${DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN/./-}-staging"
  namespace: network
spec:
  secretName: "${DOMAIN/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${DOMAIN}"
  dnsNames:
    - "${DOMAIN}"
    - "*.${DOMAIN}"
