---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-cert-manager
  namespace: flux-system
spec:
  path: ./cluster/apps/kube-system/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: apps-cert-manager-issuers
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: apps-cert-manager
#   path: ./cluster/apps/kube-system/cert-manager/issuers
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-cluster
#   interval: 30m
#   retryInterval: 1m
#   timeout: 3m
