---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-system-cert-manager
  namespace: flux-system
spec:
  path: ./cluster/apps/kube-system/cert-manager/app
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-system-cert-manager-issuers
  namespace: flux-system
spec:
  path: ./cluster/apps/kube-system/cert-manager/issuers
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
  dependsOn:
    - name: kube-system-cert-manager
