---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: system-reloader
  namespace: flux-system
spec:
  path: ./cluster/apps/system/reloader/app
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  prune: true
  wait: true
  interval: 30m
