---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-reloader
  namespace: flux-system
spec:
  path: ./cluster/apps/system/reloader/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: reloader
      namespace: system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
